In [53]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

In [54]:
df = pd.read_csv("C:/Users/bingi/Downloads/bi.csv", encoding="latin1")
df.head()

,fNAME,lNAME,Age,gender,country,residence,entryEXAM,prevEducation,studyHOURS,Python,DB
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80

In [55]:
df.rename(columns = lambda x: x.lower(), inplace = True)

In [56]:
df.rename(columns = {
    'fname' : 'First_Name',
    'lname' : 'Last_Name',
    'age' : 'Age',
    'gender' : 'Gender',
    'country' : 'Country',
    'residence' : 'Residence',
    'studyhours' : 'Studyhours',
    'python' : 'Python',
    'db' : 'Database'
},inplace = True)
df.head()

,First_Name,Last_Name,Age,Gender,Country,Residence,entryexam,preveducation,Studyhours,Python,Database
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80

In [57]:
df.rename(columns={
    'entryexam' : 'Entry_Exam',
    'preveducation' : 'Prev_Education',
},inplace = True
)
df.head()

,First_Name,Last_Name,Age,Gender,Country,Residence,Entry_Exam,Prev_Education,Studyhours,Python,Database
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80

In [58]:
df.dtypes

First_Name         object
Last_Name          object
Age                 int64
Gender             object
Country            object
Residence          object
Entry_Exam          int64
Prev_Education     object
Studyhours          int64
Python            float64
Database            int64
dtype: object

In [59]:
df['Database'].astype('float')
df.head()

,First_Name,Last_Name,Age,Gender,Country,Residence,Entry_Exam,Prev_Education,Studyhours,Python,Database
0,Christina,Binger,44,Female,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,Male,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,F,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,Female,South Africa,Sognsvann,65,High School,122,91.0,80

In [60]:
df.isnull().sum()

First_Name        0
Last_Name         0
Age               0
Gender            0
Country           0
Residence         0
Entry_Exam        0
Prev_Education    0
Studyhours        0
Python            2
Database          0
dtype: int64

In [61]:
df['Python'] = df['Python'].fillna(df['Python'].mean())

In [62]:
df.shape

(77, 11)

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   First_Name      77 non-null     object
 1   Last_Name       77 non-null     object
 2   Age             77 non-null     int64
 3   Gender          77 non-null     object
 4   Country         77 non-null     object
 5   Residence       77 non-null     object
 6   Entry_Exam      77 non-null     int64
 7   Prev_Education  77 non-null     object
 8   Studyhours      77 non-null     int64
 9   Python          77 non-null     float64
 10  Database        77 non-null     int64
dtypes: float64(1), int64(4), object(6)
memory usage: 6.7+ KB

In [64]:
df.duplicated().sum()

np.int64(0)

In [65]:
df.duplicated().sum()

np.int64(0)

In [66]:
df['Gender'].value_counts()

Gender
Female    41
Male      32
M          1
F          1
female     1
male       1
Name: count, dtype: int64

In [67]:
df['Gender'] = df['Gender'].str.lower()
df['Gender'].value_counts()

Gender
female    42
male      33
m          1
f          1
Name: count, dtype: int64

In [68]:
# Do NOT use inplace=True when assigning back
df['Gender'] = df['Gender'].replace({
    'm': 'male',
    'f': 'female'
})

# Now recompute counts
print(df['Gender'].value_counts())

Gender
female    43
male      34
Name: count, dtype: int64

In [69]:
df['Country'].unique()

array(['Norway', 'Kenya', 'Uganda', 'Rsa', 'South Africa', 'Norge',
       'norway', 'Denmark', 'Netherlands', 'Italy', 'Spain', 'UK',
       'Somali', 'Nigeria', 'Germany', 'France'], dtype=object)

In [70]:
print("Before:\n", df['Country'].unique())
df['Country'] = df['Country'].replace({
    'USA': 'United States',
    'UK': 'United Kingdom',
    'UAE': 'United Arab Emirates',
    'Indiaa': 'India',
    'INDIA': 'India',
    'norway': 'Norway',
    'Rsa': 'Russia'
})

print("After:\n", df['Country'].unique())

Before:
 ['Norway' 'Kenya' 'Uganda' 'Rsa' 'South Africa' 'Norge' 'norway' 'Denmark'
 'Netherlands' 'Italy' 'Spain' 'UK' 'Somali' 'Nigeria' 'Germany' 'France']
After:
 ['Norway' 'Kenya' 'Uganda' 'Russia' 'South Africa' 'Norge' 'Denmark'
 'Netherlands' 'Italy' 'Spain' 'United Kingdom' 'Somali' 'Nigeria'
 'Germany' 'France']

In [71]:
df['Residence'].unique()

df['Residence'] = df['Residence'].replace({
    'BI-Residence' : 'BI Residence',
    'BIResidence' : 'BI Residence',
    'BI_Residence' : 'BI Residence'
})

print("After:\n", df['Residence'].unique())

After:
 ['Private' 'Sognsvann' 'BI Residence']

In [72]:
print("Before:\n", df['Prev_Education'].unique())
df['Prev_Education'] = df['Prev_Education'].replace({
    'HighSchool': 'High School',
    'Barrrchelors': 'Bachelors',
    'Diplomaaa': 'Diploma',
    'diploma': 'Diploma',
    'DIPLOMA': 'Diploma'
})

print("After:\n", df['Prev_Education'].unique())

Before:
 ['Masters' 'Diploma' 'HighSchool' 'High School' 'Bachelors' 'Barrrchelors'
 'diploma' 'DIPLOMA' 'Diplomaaa' 'Doctorate']
After:
 ['Masters' 'Diploma' 'High School' 'Bachelors' 'Doctorate']

In [80]:
df.filter(items=[2] , axis = 0)

,First_Name,Last_Name,Age,Gender,Country,Residence,Entry_Exam,Prev_Education,Studyhours,Python,Database
2,Philip,Leo,25,male,Uganda,Sognsvann,55,High School,130,74.0,50

In [84]:
df.loc[2,:]

First_Name             Philip
Last_Name                 Leo
Age                        25
Gender                   male
Country                Uganda
Residence           Sognsvann
Entry_Exam                 55
Prev_Education    High School
Studyhours                130
Python                   74.0
Database                   50
Name: 2, dtype: object

In [90]:
df.nlargest(n = 2 ,columns='Python')

,First_Name,Last_Name,Age,Gender,Country,Residence,Entry_Exam,Prev_Education,Studyhours,Python,Database
4,Maria,Kedibone,23,female,South Africa,Sognsvann,65,High School,122,91.0,80
34,Line,Næss,25,female,Norway,BI Residence,98,High School,160,90.0,90

In [91]:
df.sort_values(ascending=False,by=['Python'])

,First_Name,Last_Name,Age,Gender,Country,Residence,Entry_Exam,Prev_Education,Studyhours,Python,Database
4,Maria,Kedibone,23,female,South Africa,Sognsvann,65,High School,122,91.0,80
50,Dag,Arnesen,30,male,Norway,BI Residence,95,Diploma,160,90.0,89
58,Morten,Olsen,46,female,Norway,Private,94,Doctorate,160,90.0,77
34,Line,Næss,25,female,Norway,BI Residence,98,High School,160,90.0,90
5,Hannah,Hansen,25,female,Norge,BI Residence,66,High School,130,88.0,59
...,...,...,...,...,...,...,...,...,...,...,...
49,Thea,Knutsen,28,male,Norway,BI Residence,69,High School,120,45.0,70
20,Prof,Birkeland,22,male,Norway,BI Residence,45,High School,116,33.0,30
32,Perry,Rønning,71,female,Norway,Private,30,Doctorate,120,31.0,42
21,Hanna,Isaksen,24,female,Norway,BI Residence,50,High School,114,30.0,50
53,Chinedu,Morison,36,male,Nigeria,Private,28,Diploma,120,15.0,67